const actionTypes = {
    REGISTER: 'REGISTER',
    CONFIRM_EMAIL: 'CONFIRM_EMAIL',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    
    // USER
    GET_CURRENT: 'GET_CURRENT',
    GET_USER_OF_TREE: "GET_USER_OF_TREE",
    GET_USER_OF_TREE_BY_ID: "GET_USER_OF_TREE_BY_ID",
    GET_USER_DETAILS: "GET_USER_DETAILS",
    UPDATE_USER: "UPDATE_USER",
    LOOK_USER: "LOOK_USER",
    // LOADING
    LOADING : 'LOADING',

    // SHOP
    GET_LIST_SHOP: "GET_LIST_SHOP",
    GET_SHOP_BY_ID: "GET_SHOP_BY_ID",
    CREATE_SHOP: "CREATE_SHOP",
    UPDATE_SHOP: "UPDATE_SHOP",
    DELETE_SHOP: "DELETE_SHOP",
    ACTIVE_SHOP: "ACTIVE_SHOP",
    CHOOSE_SHOP: "CHOOSE_SHOP",
    LOADING_SHOP : 'LOADING_SHOP',
    ERROR_SHOP : 'LOADING_SHOP',


    // Area
    GET_LIST_AREA: "GET_LIST_AREA",
    GET_AREA_BY_ID: "GET_AREA_BY_ID",
    CREATE_AREA: "CREATE_AREA",
    UPDATE_AREA: "UPDATE_AREA",
    DELETE_AREA: "DELETE_AREA",
    LOADING_AREA: 'LOADING_AREA',
    ERROR_AREA: 'LOADING_AREA',

    
    // Tables
    GET_LIST_TABLES: "GET_LIST_TABLES",
    GET_TABLES_BY_ID: "GET_TABLES_BY_ID",
    CREATE_TABLES: "CREATE_TABLES",
    UPDATE_TABLES: "UPDATE_TABLES",
    DELETE_TABLES: "DELETE_TABLES",
    LOADING_TABLES: 'LOADING_TABLES',
    ERROR_TABLES: 'LOADING_TABLES',
    
    // ERROR
    FAIL: "FAIL"
}
export default actionTypes